  METHOD if_oo_adt_classrun~main.
    DATA lt_bank_code TYPE TABLE OF yeho_t_bankcode.
    lt_bank_code = VALUE #( ( bank_code =   '0010'  bank_name =   'Türkiye Cumhuriyeti Ziraat Bankası A.Ş.' )
                            ( bank_code =   '0013'  bank_name =   'Denizbank' )
                            ( bank_code =   '0015'  bank_name =   'Türkiye Vakıflar Bankası T.A.O.' )
                            ( bank_code =   '0017'  bank_name =   'Türkiye Kalkınma Bankası A.Ş.' )
                            ( bank_code =   '0032'  bank_name =   'Türk Ekonomi Bankası A.Ş.' )
                            ( bank_code =   '0046'  bank_name =   'Akbank T.A.Ş.' )
                            ( bank_code =   '0058'  bank_name =   'Sınai Yatırım Bankası A.Ş.' )
                            ( bank_code =   '0062'  bank_name =   'Türkiye Garanti Bankası A.Ş.' )
                            ( bank_code =   '0067'  bank_name =   'Yapı ve Kredi Bankası A.Ş.'  )
                            ( bank_code =   '0087'  bank_name =   'Banca di Roma' )
                            ( bank_code =   '0091'  bank_name =   'Arap Türk Bankası A.Ş.' )
                            ( bank_code =   '0094'  bank_name =   'Bank Mellat' )
                            ( bank_code =   '0096'  bank_name =   'Turkish Bank A.Ş.' )
                            ( bank_code =   '0098'  bank_name =   'JP Morgan Chase Bank' )
                            ( bank_code =   '0100'  bank_name =   'Adabank A.Ş.'  )
                            ( bank_code =   '0103'  bank_name =   'Fiba Bank A.Ş.' )
                            ( bank_code =   '0106'  bank_name =   'PORTIGON A.G.' )
                            ( bank_code =   '0108'  bank_name =   'Turkland Bank A.Ş.' )
                            ( bank_code =   '0110'  bank_name =   'Credit Lyonnais' )
                            ( bank_code =   '0113'  bank_name =   'Marbank' )
                            ( bank_code =   '0116'  bank_name =   'TAİB Yatırım Bank A.Ş.'  )
                            ( bank_code =   '0118'  bank_name =   'Kıbrıs Kredi Bankası' )
                            ( bank_code =   '0121'  bank_name =   'Standard Chartered Yatırım Bankası Türk A.Ş.' )
                            ( bank_code =   '0123'  bank_name =   'HSBC Bank A.Ş.'  )
                            ( bank_code =   '0125'  bank_name =   'Burganbank A.Ş.' )
                            ( bank_code =   '0128'  bank_name =   'Park Yatırım Bankası'  )
                            ( bank_code =   '0132'  bank_name =   'IMKB Takas ve Saklama Bankası A.Ş.'  )
                            ( bank_code =   '0134'  bank_name =   'Denizbank A.Ş.'  )
                            ( bank_code =   '0136'  bank_name =   'Okan Yatırım Bankası A Ş'  )
                            ( bank_code =   '0138'  bank_name =   'Diler Yatırım Bankası A.Ş.'  )
                            ( bank_code =   '0140'  bank_name =   'Credit Suisse First Boston İstanbul Şubesi'  )
                            ( bank_code =   '0142'  bank_name =   'Bank Pozitif Kredi ve Kalkınma Bankası A.Ş.' )
                            ( bank_code =   '0145'  bank_name =   'Morgan Guarenty Trusy Company' )
                            ( bank_code =   '0147'  bank_name =   'Bank of Tokyo -Mitsubishi UFJ Turkey A.Ş.' )
                            ( bank_code =   '0223'  bank_name =   'Albaraka Türk Katılım Bankası A.Ş.' )
                            ( bank_code =   '0012'  bank_name =   'Türkiye Halk Bankası A.Ş.' )
                            ( bank_code =   '0014'  bank_name =   'Türkiye Sınai Kalkınma Bankası A.Ş.' )
                            ( bank_code =   '0016'  bank_name =   'Türkiye İhracat Kredi Bankası A.Ş. (Eximbank)' )
                            ( bank_code =   '0029'  bank_name =   'Birleşik Fon Bankası A.Ş. (Bayındırbank A.Ş.)' )
                            ( bank_code =   '0034'  bank_name =   'Aktif Yatırım Bankası A.Ş.' )
                            ( bank_code =   '0048'  bank_name =   'HSBC Bank A.Ş.'  )
                            ( bank_code =   '0059'  bank_name =   'Şekerbank T.A.Ş.'  )
                            ( bank_code =   '0064'  bank_name =   'Türkiye İş Bankası A.Ş.' )
                            ( bank_code =   '0071'  bank_name =   'Fortis Bank (TEB)' )
                            ( bank_code =   '0088'  bank_name =   'The Royal Bank of Scotland'  )
                            ( bank_code =   '0092'  bank_name =   'Citibank N.A.' )
                            ( bank_code =   '0095'  bank_name =   'BCCI'  )
                            ( bank_code =   '0097'  bank_name =   'Habib Bank Limited' )
                            ( bank_code =   '0099'  bank_name =   'ING Bank (Oyak Bank)'  )
                            ( bank_code =   '0101'  bank_name =   'Türk Sakura Bank A.Ş.' )
                            ( bank_code =   '0104'  bank_name =   'IMPEXBANK' )
                            ( bank_code =   '0107'  bank_name =   'BNP-Ak-Dresdner Bank A.Ş.' )
                            ( bank_code =   '0109'  bank_name =   'ICBC Turkey Bank A.Ş.'  )
                            ( bank_code =   '0111'  bank_name =   'Finansbank A.Ş.' )
                            ( bank_code =   '0115'  bank_name =   'Deutsche Bank A.Ş.'  )
                            ( bank_code =   '0117'  bank_name =   'Turizm Yatırım ve Ticaret Bank A.Ş.' )
                            ( bank_code =   '0119'  bank_name =   'Birleşik Yatırım'  )
                            ( bank_code =   '0122'  bank_name =   'Societe Generale'  )
                            ( bank_code =   '0124'  bank_name =   'Alternatifbank A.Ş.' )
                            ( bank_code =   '0127'  bank_name =   'KentBank'  )
                            ( bank_code =   '0129'  bank_name =   'Tat Yatırım Bankası A.Ş.'  )
                            ( bank_code =   '0133'  bank_name =   'ING BANK'  )
                            ( bank_code =   '0135'  bank_name =   'Anadolubank A.Ş.'  )
                            ( bank_code =   '0137'  bank_name =   'Rabobank Nederland İstanbul Merkez Şubesi' )
                            ( bank_code =   '0139'  bank_name =   'GSD Yatırım Bankası A.Ş.'  )
                            ( bank_code =   '0141'  bank_name =   'Nurol Yatırım Bankası A.Ş.'  )
                            ( bank_code =   '0144'  bank_name =   'Atlas Yatırım Bankası A.Ş.'  )
                            ( bank_code =   '0146'  bank_name =   'OdeaBank A.Ş.' )
                            ( bank_code =   '0148'  bank_name =   'Intesa SanPaolo SPA İtalya' )
                            ( bank_code =   '0203'  bank_name =   'Albaraka Türk Katılım Bankası A.Ş.' )
                            ( bank_code =   '0204'  bank_name =   'Family Finans Kurumu'  )
                            ( bank_code =   '0205'  bank_name =   'Kuveyt Türk Katılım Bankası A.Ş.'  )
                            ( bank_code =   '0206'  bank_name =   'Türkiye Finans Katılım Bankası A.Ş.' )
                            ( bank_code =   '0208'  bank_name =   'Asya Katılım Bankası A.Ş.' )
                            ( bank_code =   '0209'  bank_name =   'Ziraat Katılım Bankası A.Ş.' )
                            ( bank_code =   '0210'  bank_name =   'Vakıf Katılım Bankası A.Ş.'  )
                            ( bank_code =   '0211'  bank_name =   'Türkiye Emlak Katılım Bankası A.Ş.' ) ).
    MODIFY yeho_t_bankcode FROM TABLE @lt_bank_code.
    COMMIT WORK AND WAIT.
  ENDMETHOD.